apiVersion: v1
kind: ConfigMap
metadata:
  name: "mysql-backup-hook-config-map"
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
data:
  entrypoint.sh: |-
    #!/bin/sh
    cmd="/docker-entrypoint.sh mysql"
    eval "${cmd}" & disown;
    
    mysql_ready() {
        mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD -e "SELECT 1" > /dev/null 2>&1
    }
    
    until mysql_ready; do
      sleep 5;
    done;
    mysqldump --single-transaction -h localhost -u $MYSQL_USER -p$MYSQL_PASSWORD {{ template "mysql.DatabaseName" . }} > /mysql_backups/$BACKUP_NAME
