apiVersion: v1
kind: Secret
metadata:
  name: db-details
data:
  db_user: { { .Values.mysql.username | b64enc | quote } }
#  { { if .Values.mysql.password } }
  db_password: { { .Values.mysql.password | b64enc | quote } }
#  {{ else }}
#  db_password: {{ randAlphaNum 15 | b64enc | quote }}
  # `index` function is necessary because the property name contains a dash.
  # Otherwise (...).data.db_password would have worked too.
#  db_password:  {{ index (lookup "v1" "Secret" .Release.Namespace "db-details").data "db_password" }}
  db_root_password: { { .Values.mysql.root_password | b64enc | quote } }
