apiVersion: v1
kind: Secret
metadata:
  name: db-details
type: Opaque
data:
  db_user: {{ .Values.mysql.username | b64enc | quote }}
  db_password: {{ .Values.mysql.password | b64enc | quote }}
  db_root_password: {{ .Values.mysql.root_password | b64enc | quote }}
