appVolumeMounts:
  nextcloud-data:
    emptyDir: true
    mountPath: /var/www
cronjob:
  enabled: false
  schedule: 1 */24 * * *
dnsConfig:
  options: []
emptyDirVolumes: true
environmentVariables: []
image:
  pullPolicy: IfNotPresent
  repository: nextcloud
  tag: 24.0.5
ixChartContext: {}
nextcloud:
  datadir: /var/www/html/data
  host: nextcloud.kube.home
  password: changeme
  username: admin
nginx:
  image:
    pullPolicy: IfNotPresent
    repository: nginx
    tag: 1.21.3
mysqlAppVolumeMounts:
  mysql-backup:
    emptyDir: true
    mountPath: /mysql_backups
  mysql-data:
    emptyDir: true
    mountPath: /var/lib/mysql/data
mysql:
  image:
    pullPolicy: IfNotPresent
    repository: mysql
    tag: 8.0.30
  backupVolume:
    datasetName: ix-mysql_backups
    mountPath: /mysql_backups
  dataVolume:
    datasetName: ix-mysql_data
    mountPath: /var/lib/mysql/data
  username: db_user
  password: db_password
  root_password: iamgROOT
service:
  nodePort: 31000
updateStrategy: Recreate
useServiceNameForHost: true
